version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: todolist-mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  todoapi:
    depends_on:
      - mysqldb
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /usr/src/todolistapi
    container_name: todolist-api
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_DOCKER_PORT=$MYSQL_DOCKER_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - JWT_SECRET=$JWT_SECRET
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    stdin_open: true
    tty: true
  todomobile:
    depends_on:
      - mysqldb
      - todoapi
    build:
      context: ./mobile
      dockerfile: Dockerfile
    working_dir: /usr/src/todolistmobile
    container_name: todolist-mobile
    restart: unless-stopped
    env_file: .env
    environment:
      - API_URL=http://mysqldb:$NODE_DOCKER_PORT/
      - JWT_SECRET=$JWT_SECRET
      - REACT_NATIVE_PACKAGER_HOSTNAME=$REACT_NATIVE_PACKAGER_HOSTNAME
    ports:
      - 8081:8081
    stdin_open: true
    tty: true
    