version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: todolist-mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_TCP_PORT=$DB_DOCKER_PORT
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
  todoapi:
    depends_on:
      - mysqldb
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /usr/src/todolistapi
    container_name: todolist-api
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=mysqldb
      - DB_DOCKER_PORT=$DB_DOCKER_PORT
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - JWT_SECRET=$JWT_SECRET
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
  todomobile:
    depends_on:
      - mysqldb
      - todoapi
    build:
      context: ./mobile
      dockerfile: Dockerfile
    working_dir: /usr/src/todolistmobile
    container_name: todolist-mobile
    restart: unless-stopped
    env_file: .env
    environment:
      - API_URL=http://mysqldb:$NODE_DOCKER_PORT/
      - JWT_SECRET=$JWT_SECRET
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.79
    ports:
      - 8081:8081
    stdin_open: true
    tty: true
    