version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: todolist-mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_TCP_PORT=$DB_DOCKER_PORT
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
  app:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/todolist
    container_name: todolist-api
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mysqldb
      - NODE_HOST=$NODE_HOST
      - DB_DOCKER_PORT=$DB_DOCKER_PORT
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
